"use client";

import React from "react";
import { X, CheckCircle2, AlertCircle, Clock, ShieldCheck, Cpu } from "lucide-react";
import { OrderRecord } from "../../lib/types";

interface OrderDrawerProps {
  order: OrderRecord | null;
  onClose: () => void;
}

export default function OrderDrawer({ order, onClose }: OrderDrawerProps) {
  if (!order) return null;

  const isFilled = order.status === "FILLED";
  const isRejected = order.status === "REJECTED";

  const statusColor = isFilled 
    ? "text-[#22C55E] bg-[#22C55E]/15 border-[#22C55E]/40" 
    : isRejected 
    ? "text-[#EF4444] bg-[#EF4444]/15 border-[#EF4444]/40" 
    : "text-[#F59E0B] bg-[#F59E0B]/15 border-[#F59E0B]/40";

  const orderTime = new Date(order.timestamp).toLocaleString();
  const notional = (order.price ?? 0) * order.quantity;

  return (
    <div className="fixed inset-0 z-50 flex justify-end bg-black/60 backdrop-blur-xs font-mono select-none">
      <div className="w-full max-w-md bg-[#131822] border-l border-[#2E3A4E] h-full flex flex-col shadow-2xl animate-in slide-in-from-right duration-200">
        {/* Drawer Header */}
        <div className="p-3.5 bg-[#0D1117] border-b border-[#1E2635] flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-[#007AFF]"></span>
            <span className="font-bold text-white text-xs tracking-wider">
              ORDER LIFECYCLE AUDIT: {order.order_id}
            </span>
          </div>
          <button onClick={onClose} className="text-[#4F596A] hover:text-white transition-colors">
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Drawer Content */}
        <div className="p-4 space-y-5 overflow-y-auto flex-1 text-xs">
          {/* Status Banner */}
          <div className="p-3 bg-[#0D1117] border border-[#1E2635] flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="text-[#8A94A6]">STATUS:</span>
              <span className={`px-2 py-0.5 text-[10px] font-bold border ${statusColor}`}>
                {order.status}
              </span>
            </div>
            <span className="text-[#38BDF8] text-[10px] font-bold">{order.execution_mode}</span>
          </div>

          {/* Primary Order Metrics Grid */}
          <div className="grid grid-cols-2 gap-2 text-xs">
            <div className="p-2.5 bg-[#0D1117] border border-[#1E2635]">
              <span className="text-[10px] text-[#4F596A] block">ASSET SYMBOL</span>
              <span className="font-bold text-white text-sm tracking-tight">{order.symbol}</span>
            </div>
            <div className="p-2.5 bg-[#0D1117] border border-[#1E2635]">
              <span className="text-[10px] text-[#4F596A] block">SIDE</span>
              <span className={`font-bold text-sm ${order.side === "BUY" ? "text-[#22C55E]" : "text-[#EF4444]"}`}>
                {order.side}
              </span>
            </div>
            <div className="p-2.5 bg-[#0D1117] border border-[#1E2635]">
              <span className="text-[10px] text-[#4F596A] block">EXECUTED QUANTITY</span>
              <span className="font-bold text-white mono-num">{order.quantity} shares</span>
            </div>
            <div className="p-2.5 bg-[#0D1117] border border-[#1E2635]">
              <span className="text-[10px] text-[#4F596A] block">PRICE PER UNIT</span>
              <span className="font-bold text-white mono-num">₹{order.price?.toFixed(2) || "---"}</span>
            </div>
            <div className="p-2.5 bg-[#0D1117] border border-[#1E2635] col-span-2 flex justify-between items-center">
              <span className="text-[10px] text-[#4F596A]">TOTAL NOTIONAL VALUE</span>
              <span className="font-bold text-[#38BDF8] mono-num text-sm">
                ₹{notional.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
              </span>
            </div>
          </div>

          {/* Execution Timeline */}
          <div className="space-y-2">
            <div className="text-[10px] font-bold text-[#4F596A] tracking-wider border-b border-[#1E2635] pb-1">
              EXECUTION MILESTONES & AUDIT LOG
            </div>

            <div className="space-y-3 pl-2 border-l border-[#1E2635] ml-2">
              <div className="relative pl-4">
                <span className="absolute -left-[17px] top-1 w-2 h-2 rounded-full bg-[#22C55E]"></span>
                <div className="flex justify-between items-center text-[11px]">
                  <strong className="text-white">Signal Dispatched</strong>
                  <span className="text-[#4F596A] mono-num text-[10px]">{orderTime}</span>
                </div>
                <div className="text-[10px] text-[#8A94A6]">Generated by systematic alpha strategy</div>
              </div>

              <div className="relative pl-4">
                <span className="absolute -left-[17px] top-1 w-2 h-2 rounded-full bg-[#38BDF8]"></span>
                <div className="flex justify-between items-center text-[11px]">
                  <strong className="text-white">Pre-Trade Risk Engine Passed</strong>
                  <span className="text-[#22C55E] text-[10px] font-bold">100% OK</span>
                </div>
                <div className="text-[10px] text-[#8A94A6]">Concentration, daily loss, and drawdown validated</div>
              </div>

              <div className="relative pl-4">
                <span className={`absolute -left-[17px] top-1 w-2 h-2 rounded-full ${isFilled ? "bg-[#22C55E]" : "bg-[#EF4444]"}`}></span>
                <div className="flex justify-between items-center text-[11px]">
                  <strong className="text-white">{isFilled ? "Broker Acknowledged & Filled" : "Order Blocked / Rejected"}</strong>
                  <span className="text-[#8A94A6] mono-num text-[10px]">18ms latency</span>
                </div>
                <div className="text-[10px] text-[#8A94A6]">
                  {order.rejection_reason || `Filled via simulated broker matching engine with 5.0 bps slippage`}
                </div>
              </div>
            </div>
          </div>

          {/* Transaction Friction Breakdown */}
          <div className="p-3 bg-[#0D1117] border border-[#1E2635] space-y-1.5 text-[11px]">
            <div className="text-[10px] font-bold text-[#4F596A] tracking-wider mb-1">
              ESTIMATED TRANSACTION FRICTION
            </div>
            <div className="flex justify-between text-[#8A94A6]">
              <span>Modeled Slippage (5.0 bps):</span>
              <span className="text-white mono-num">₹{(notional * 0.0005).toFixed(2)}</span>
            </div>
            <div className="flex justify-between text-[#8A94A6]">
              <span>Exchange & Clearing Fees (3.35 bps):</span>
              <span className="text-white mono-num">₹{(notional * 0.000335).toFixed(2)}</span>
            </div>
            <div className="flex justify-between text-[#8A94A6] border-t border-[#1E2635] pt-1">
              <span className="font-bold text-white">Net Execution Cost:</span>
              <span className="font-bold text-[#F59E0B] mono-num">₹{(notional * 0.000835).toFixed(2)}</span>
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="p-3 bg-[#0D1117] border-t border-[#1E2635] flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-1.5 bg-[#131822] hover:bg-[#1A2230] border border-[#1E2635] text-white text-xs font-bold transition-colors"
          >
            CLOSE INSPECTOR
          </button>
        </div>
      </div>
    </div>
  );
}
